# How to use?

# Dataset
> Download dataset from below location or you can make a online script. But i will prefer make a local machine script.
https://www.kaggle.com/paultimothymooney/chest-xray-pneumonia

## Steps to use

> Step1: Run this file to create_model. It can take a long time to generate model depending on your machine configuration and data. 
> Step2: After that it will generate one model file image_classifier_big.sav. You can see already there is image_classifier_big.sav file. This is our trained model which was generated by step 1. So instead of creating
a new model you can use it but keep it in mind that this model is specifically trained for given data. If you want to change images or some change in model and data then you have to regenrate it using step1.
> Step 3: Execute load_model.py to predict

*Note: all the path and folder system were set according to my computer. Please do not forget to change them. Before running file download dataset to your local system and set the correct file path in both python scripts.